tidy and fix magefile
michaelneale/ssi-sdk pull request #3
Opened 2022-09-27 21:25 UTC by decentralgabe

2022-10-03 18:33 UTC, decentralgabe commented
@michaelneale what do you think?

2022-10-03 20:23 UTC, michaelneale commented
Looks good. Didn’t think of the mobile requirement, nice one.

2022-10-06 03:45 UTC, michaelneale requested changes
I think there was some hard coding

2022-10-06 03:45 UTC, michaelneale commented on magefile.go
> +		logrus.Info("Successfully installed govuln")
@decentralgabe this sees to be hard coded - should be `goPackage` right?

2022-10-06 16:53 UTC, decentralgabe commented
@michaelneale I apologize, I was impatient and merged this into the ssi-sdk project.

2022-10-06 16:53 UTC, closed without merging